export const URL_API_DATA = "https://backend-energy.onrender.com/api/data?id=";

export const ARRAY_HIDROELECTRICS = [
  "Algarrobos 1",
  "Algarrobos 2",
  "Baitún 1",
  "Baitún 2",
  "Baitún 4",
  "Bajo del Totuma",
  "Bajo Mina 1",
  "Bajo Mina 2",
  "Bajo Mina 3",
  "Barro Blanco 1",
  "Barro Blanco 2",
  "Barro Blanco 3",
  "Bayano 1",
  "Bayano 2",
  "Bayano 3",
  "Bonyic 1",
  "Bonyic 2",
  "Bonyic 3",
  "Bugaba I 1",
  "Bugaba I 2",
  "Bugaba I 3",
  "Bugaba II 1",
  "Bugaba II 2",
  "Bugaba II 3",
  "Changuinola 1",
  "Changuinola 2",
  "Changuinola 3",
  "Cochea 1",
  "Cochea 2",
  "Concepción 1",
  "Concepción 2",
  "Dolega 1",
  "Dolega 2",
  "Dolega 3",
  "Eco Hidro Tizingal",
  "El Alto 1",
  "El Alto 2",
  "El Alto 3",
  "El Alto 4",
  "Estí 1",
  "Estí 2",
  "Estrella 1",
  "Estrella 2",
  "Fortuna 1",
  "Fortuna 2",
  "Fortuna 3",
  "Fraile 1",
  "Fraile 2",
  "Fraile 3",
  "Gatún 1",
  "Gatún 2",
  "Gatún 3",
  "Gatún 4",
  "Gatún 5",
  "Gatún 6",
  "Gualaca 1",
  "Gualaca 2",
  "La Cuchilla 1",
  "La Cuchilla 2",
  "La Potra 1",
  "La Potra 2",
  "La Potra 3",
  "La Potra 4",
  "Las Cruces 1",
  "Las Cruces 2",
  "Las Cruces 3",
  "Lorena 1",
  "Lorena 2",
  "Macano 1",
  "Macano 2",
  "Macano 3",
  "Madden 1",
  "Madden 2",
  "Madden 3",
  "Mendre 1",
  "Mendre 2",
  "Mendre II 1",
  "Mendre II 2",
  "M. Monte 1",
  "M. Monte 2",
  "Monte Lirio 1",
  "Monte Lirio 2",
  "Monte Lirio 3",
  "Pando 1",
  "Pando 2",
  "Paso Ancho 1",
  "Paso Ancho 2",
  "Pedregalito I 1",
  "Pedregalito I 2",
  "Pedregalito I 3",
  "Pedregalito II 1",
  "Pedregalito II 2",
  "Perlas Norte 1",
  "Perlas Norte 2",
  "Perlas Sur 1",
  "Perlas Sur 2",
  "Planetas I 1",
  "Planetas I 2",
  "Planetas I 3",
  "Planetas II 1",
  "Planetas II 2",
  "Prudencia 1",
  "Prudencia 2",
  "RP-490 1",
  "RP-490 2",
  "Salsipuedes 1",
  "Salsipuedes 2",
  "Salsipuedes 3",
  "San Andrés 1",
  "San Andrés 2",
  "San Lorenzo 1",
  "San Lorenzo 2",
  "Valles 1",
  "Valles 2",
  "Yeguada 1",
  "Yeguada 2",
  "Yeguada 3",
];

export const ARRAY_TERMINC = [
  "ACP Miraflores 5",
  "ACP Miraflores 9",
  "ACP Miraflores 10",
  "BLM 6",
  "BLM 8",
  "CADASA 1",
  "Cativá 1",
  "Cativá 2",
  "Cativá 3",
  "Cativá 4",
  "Cativá 5",
  "Cativá 6",
  "Cativá 7",
  "Cativá 8",
  "Cativá 9",
  "Cativá 10",
  "Cobre Panamá 1",
  "Cobre Panamá 2",
  "Costa Norte 1",
  "Costa Norte 2",
  "Costa Norte 3",
  "Costa Norte 4",
  "Pacora 1",
  "Pacora 2",
  "Pacora 3",
  "PanAm 1",
  "PanAm 2",
  "PanAm 3",
  "PanAm 4",
  "PanAm 5",
  "PanAm 6",
  "PanAm 7",
  "PanAm 8",
  "PanAm 9",
  "Sparkle Power 1",
  "Sparkle Power 2",
  "Sparkle Power 3",
  "Sparkle Power 4",
  "Sparkle Power 5",
  "Sparkle Power 6",
  "Sparkle Power 7",
  "Sparkle Power 8",
  "Termocolón 1",
  "Termocolón 2",
  "Termocolón 3",
  "Tropitérmica 1",
  "Tropitérmica 2",
  "Tropitérmica 3",
];

export const ARRAY_SOLAR = [
  "Andrea's Power",
  "Antón Solar 1",
  "Baco Solar",
  "Bejuco Solar",
  "Caoba Solar",
  "Cedro Solar",
  "Chame Solar",
  "Coclé Solar 1",
  "Daconan Solar",
  "Divisa Solar",
  "Don Félix",
  "Ecoener San Juan",
  "Ecosolar",
  "Ecosolar 2",
  "Ecosolar 3",
  "Ecosolar 4",
  "Ecosolar 5",
  "El Espinal",
  "El Fraile Solar 1",
  "Estrella Solar",
  "Farallón II",
  "Fotovoltaica Santiago Gen 1",
  "Ikako",
  "Ikako I",
  "Ikako II",
  "Ikako III",
  "Jagüito Solar",
  "La Esperanza Solar 20 MW",
  "Las Mendozas Solar",
  "Macano Solar",
  "Madre Vieja Solar",
  "Mayorca Solar",
  "Mendre Solar",
  "Milton Solar",
  "Oro Solar",
  "Pacora II",
  "Panasolar",
  "Panasolar II",
  "Panasolar III",
  "Parque Solar Prudencia",
  "Pedregalito Solar Power",
  "Pesé Solar",
  "Río de Jesús Solar",
  "Rodeo Solar",
  "Sarigua",
  "Sol de David",
  "Sol Real",
  "Solar Bugaba",
  "Solar Caldera",
  "Solar Chiriquí",
  "Solar Coclé",
  "Solar Fotovoltaica Penonomé",
  "Solar Los Ángeles",
  "Solar Paris",
  "Solar Pocrí",
  "Sunrise MASPV 1",
  "Vista Alegre	",
];

export const ARRAY_EOLICA = [
  "Marañón GGC1",
  "Nvo. Chagres I GGC1",
  "Nvo. Chagres I GGC2",
  "Nvo. Chagres I GGC3",
  "Nvo. Chagres II GGC1",
  "Nvo. Chagres II GGC2",
  "Nvo. Chagres II GGC3",
  "Portobelo GGC1",
  "R. Vientos I GGC1",
  "R. Vientos I GGC2",
  "R. Vientos II GGC1",
  "R. Vientos II GGC2",
  "Toabré",
];
